
# Project information
site_name: 'Minio Fileserver'
site_description: 'Docker image that provides volumes to be shared with other containers of Daspanel system. It also provides an S3 compatible server using Minio.'
site_author: 'Abner G Jacobsen'
site_url: 'https://daspanel.github.io/minio-fileserver'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/daspanel/minio-fileserver'

# Copyright
copyright: 'Copyright (c) 2016 Abner G Jacobsen'

# Documentation and theme
docs_dir: 'docs'
site_dir: 'site_mkdocs'

theme: 'material'
#theme_dir: docs/custom_theme
#extra_css: [ custom_theme/extra.css ]

# Google Analytics
#google_analytics:
#  - 'UA-XXXXXXXX-X'
#  - 'auto'

# Options
extra:
  version: '0.1.0'
  logo: 'images/logo.png'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
#  i18n:
#    prev: 'Previous'
#    next: 'Next'
  author:
    github: 'daspanel'
#    twitter: 'my-twitter-handle'

# From https://github.com/juttle/juttle/blob/master/mkdocs.yml http://juttle.github.io/juttle/
# http://squidfunk.github.io/mkdocs-material/getting-started/#full-example

# Extensions
markdown_extensions:
#  - codehilite(css_class=code)
  - admonition
#  - toc:
#      permalink: '#'


# use_directory_urls: true

# Pages with ___Title are hidden from left sidebar menu.
pages:

# Pages with ___Title are hidden from left sidebar menu.

#- Introduction:
#   - 'About': 'index.md'
#   - '____ Docs README': 'README.md'
#   - '____ Doc Template': 'doc_templates/template.md'
#   - '____ Juttle Doc Template': 'doc_templates/juttle_TEMPLATE.md'
#   - '____ Sample Datasets': 'examples/datasets/README.md'

- Home: 'index.md'
- User Guide:
    - 'Basic': 'help/index.md'
    - 'Usingh docker-compose': 'help/compose.md'
    - 'Advanced': 'help/advanced.md'
    - 'Development': 'help/development.md'
    - 'How To': 'howto/index.md'
- Issues: 'issues.md'
- Contributing: 'contributing.md'
- About:
    - 'Authors': 'authors.md'
    - 'Changelog': 'changelog.md'

